### ISSUE TITLE
Error: addComponentAsRefTo(...) 

### ISSUE THREAD

**Issue by HorseBinky** [ABASystems/react-keyed-file-browser#3]
Hi!

After a long search I found this nice file browser.  When I try to include it into my project the following error occures:
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Maybe I used the component in the wrong way.
I checked if react was loaded multiple times, but I was not successful. All other workarounds like "npm ls" did not work either .

I would be really thankful for any help!

Greetz

Stefan

**Comment by anggao** [comment]
found the same issue

**Comment by HorseBinky** [comment]
Found a solution which worked in my case:
I changed the order in my package.json so that "react-keyed-file-browser" comes before "react" and "react-dom"

**Comment by anggao** [comment]
@HorseBinky thanks! but I still have the issue..

**Comment by HorseBinky** [comment]
I had to uninstall the filebrowser, react and react-dom before making a fresh install of all from the changed package.json

**Comment by sfreeman422** [comment]
I am actually receiving the same issue, even after manually changing my package.json to load react-keyed-file-browser before react and react-dom. I removed my node_modules folder then reinstall fresh with an npm install and I still receive this error. Anyone got any other ideas?

**Comment by jonjomckay** [comment]
@sfreeman422 try installing the package as a git reference instead of straight from npm - I pull requested a change that should fix this a few days but I don't think it's been released to npm just yet!

**Comment by sichvoge** [comment]
@jonjomckay any plans to release it on npm? unfortunately, there is no `dist` folder so that it will work to reference the github repo in package.json

**Comment by estuart** [comment]
Has anyone found a solution to this? I installed straight from the git reference as suggested and am still having the same issue.

**Comment by jonjomckay** [comment]
@sichvoge this isn't my repository :) releasing a new version is something that's up to @bor3ham or @aidanlister I presume

**Comment by aidanlister** [comment]
Would anyone be interested in helping us maintain this? We're smashed at the moment. It's a core part of our product so we'll catch up shortly, but if you need anything urgent I'm happy to add someone as a maintainer.

**Comment by cdxOo** [comment]
For those trying to make this work via the github repository:

````bash
npm install --save https://github.com/ABASystems/react-keyed-file-browser.git
cd node_modules/react-keyed-file-browser
curl -O https://raw.githubusercontent.com/ABASystems/react-keyed-file-browser/master/webpack.config.js
sed -i s/\(node_modules\)/node_modules.*node_modules/g webpack.config.js
npm install
rm -r node_modules/react{,-dom}
````
Notes:
 - npm install somehow eats the webpack config file so we need to retrieve the file manually
 - the sed line is due to the fact that we are already in a node_modules folder and the original regex matches any occurence of "node_modules" in the absolute path of the file; i.e.: the loader would never be used in this case
 - if you keep the locally installed versions of react/react-dom in the module you'll still get the error, even if those modules are the same version as those you are using in your project

**Comment by jarekwg** [comment]
Hey all, thanks for being patient.
1.0.2 published.

I believe this can be closed now?
